### PR TITLE
Use @eth-optimism/dev

### PR DESCRIPTION
**Pull request by platocrat**
Use `@eth-optimism/dev`

### CODE REVIEW

**Comment by tynes** [comment]
The `@` in the branch name is causing CI to fail. Probably would be faster if you submitted a PR with a different branch name

**Comment by platocrat** [comment]
oh, hehe. I'll do that

**Comment by tynes** [comment]
Sorry about that! Will try to fix this in the future

**Comment by platocrat** [comment]
no worries!

**Pull request closed without merging**
